---
sidebar: sidebar 
permalink: task_cli_deploy_image_add.html 
keywords: administer, administering, cli, deploy, ontap select image, add 
summary: 您可以將ONTAP Select映像新增至 Deploy 管理公用程式實例。安裝映像後，您可以在部署ONTAP Select叢集時使用它。 
---
= 將ONTAP Select映像新增至 Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以將ONTAP Select映像新增至 Deploy 管理公用程式實例。安裝映像後，您可以在部署ONTAP Select叢集時使用它。



== 開始之前

從高層次來看，將ONTAP Select映像新增至 Deploy 實例的過程包含四個步驟：

. 下載安裝映像
. 將安裝映像上傳到 Deploy 虛擬機
. 新增安裝映像
. 顯示可用的安裝映像


在將任何新的ONTAP Select映像新增至 Deploy 之前，您應該先刪除所有不需要的映像。


NOTE: 您只能新增版本低於 Deploy 實用程式實例所含原始版本的ONTAP Select映像。不支援添加NetApp提供的ONTAP Select更高版本。



== 下載安裝映像

若要開始將ONTAP Select映像新增至 Deploy 公用程式實例，您必須從NetApp支援網站下載安裝映像。 ONTAPONTAP Select安裝映像的格式為單一壓縮檔。

.步驟
. 使用 Web 瀏覽器造訪NetApp支援站點，然後按一下「支援快速連結」。
. 點擊“熱門任務”下的“下載軟體”並登入網站。
. 點擊“尋找您的產品”。
. 向下捲動並按一下 * ONTAP Select*。
. 在*其他可用選擇軟體*下點選*部署升級、節點升級、映像安裝*。
. 選擇所需的升級包版本。
. 查看最終使用者授權協議 (EULA)，然後按一下「接受並繼續」*。
. 選擇並下載適當的包，根據您的環境需求回應所有提示。




== 將安裝映像上傳到 Deploy

取得ONTAP Select安裝映像後，您必須將該檔案上傳到 Deploy 虛擬機器。

.開始之前
您必須在本機工作站上擁有可用的安裝映像檔。您還必須擁有 Deploy 管理員使用者帳戶的密碼。

.關於此任務
此任務描述了將檔案上傳到 Deploy 虛擬機器的一種方法。可能還有其他更適合您環境的選項。

.步
. 在本機工作站的命令 shell 中，將映像檔上傳到 Deploy 虛擬機器。
+
例子

+
....
scp image_v_93_install_esx.tgz admin@10.234.81.101:/home/admin (provide password when prompted)
....
+
例子

+
....
sftp admin@10.234.81.101 (provide password when prompted)
put image_v_93_install_esx.tgz
exit
....


.結果
節點安裝檔案儲存在管理員使用者的主目錄中。



== 新增安裝映像

您可以將ONTAP Select安裝映像新增至部署映像目錄，以便在部署新叢集時可以使用它。

.開始之前
您必須知道安裝映像檔在 Deploy 實用程式虛擬機器中的哪個目錄中。假設該檔案位於管理員的主目錄中。

.步驟
. 使用管理員 (admin) 帳戶透過 SSHSign inDeploy 實用程式 CLI。
. 啟動 Bash shell：
+
`shell bash`

. 將安裝映像檔放入映像目錄中。
+
例子
`tar -xf image_v_93_install_esx.tgz -C /opt/netapp/images/`





== 顯示可用的安裝映像

您可以顯示部署新叢集時可用的ONTAP Select映像。

.步驟
. 造訪部署實用程式虛擬機器上的線上文件網頁，並使用管理員 (admin) 帳戶登入：
+
`\http://<FQDN|IP_ADDRESS>/api/ui`

+
使用 Deploy 虛擬機器的網域名稱或 IP 位址。

. 導航至頁面底部並點擊*部署*，然後點擊*取得/映像*。
. 按一下「試用！」以顯示可用的ONTAP Select映像。
. 確認所需影像可用。

