---
sidebar: sidebar 
permalink: task_cli_upgrade_esxi65.html 
keywords: administer, administering, cli, esxi, upgrade, esxi 6.5 
summary: 如果您在 VMware ESXi 上執行ONTAP Select ，則可以將 ESXi 軟體從早期支援的版本升級到 ESXi 7.0 或更高版本。在升級之前，您應該了解升級流程並選擇合適的升級步驟。 
---
= 將ONTAP Select VMware ESXi 升級到版本 7.0 或更高版本
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果您在 VMware ESXi 上執行ONTAP Select ，則可以將 ESXi 軟體從早期支援的版本升級到 ESXi 7.0 或更高版本。在升級之前，您應該了解升級流程並選擇合適的升級步驟。



== 開始之前

在升級託管ONTAP Select叢集的虛擬機器管理程式上的 ESXi 軟體之前，您應該準備並選擇適合您環境的升級流程。


CAUTION: 如果您選擇升級至 VMware ESXi 6.5，則應升級至 ESXi U2（內部版本 8294253）或更高版本。使用 ESXi 6.5 U1 可能會導致虛擬機器因已知的 VMware 錯誤而發生故障。



=== 熟悉如何升級 VMware ESXi

ESXi 軟體升級是 VMware 描述和支援的過程。使用ONTAP Select時，虛擬機器管理程式升級過程是整個升級過程的一部分。有關更多信息，請參閱 VMware 文件。



=== 選擇升級程序

有多種升級程序可供選擇。您應該根據以下條件選擇適用的程序：

* ONTAP Select叢集大小 支援單節點和多節點叢集。
* 無論是否使用 Deploy 實用程序，都可以使用ONTAP Select Deploy 升級。



TIP: 您應該選擇使用部署管理公用程式的升級過程。

使用 Deploy 管理公用程式執行 ESXi 升級是更通用且更具彈性的選項。但是，在某些情況下，Deploy 可能無法使用或無法使用。例如，早期版本的ONTAP Select和 Deploy 管理實用程式不支援升級到 ESXi 7.0。

如果您正在使用這些早期版本並嘗試升級， ONTAP Select虛擬機器可能會處於無法啟動的狀態。在這種情況下，您必須選擇不使用 Deploy 的升級程序。請參閱link:https://mysupport.netapp.com/site/bugs-online/product/ONTAPSELECT/BURT/1172198["1172198"^]了解更多。



=== 升級 Deploy 管理實用程序

在使用 Deploy 公用程式執行升級程序之前，您可能需要升級 Deploy 執行個體。通常，您應該升級到最新版本的 Deploy。 Deploy實用程式必須支援您正在使用的ONTAP Select版本。有關更多信息，請參閱ONTAP Select發行說明。



=== 更新過程完成後

如果您選擇使用 Deploy 公用程式的升級過程，則應在所有節點升級完成後使用 Deploy 執行叢集刷新操作。有關更多信息，請參閱刷新 Deploy 叢集配置。



== 使用 Deploy 升級單節點集群

您可以使用 Deploy 管理公用程式作為升級託管ONTAP Select單節點叢集的 VMware ESXi 虛擬機器管理程式的一部分。

.步驟
. 使用管理員帳戶透過 SSHSign inDeploy 實用程式 CLI。
. 將節點移至離線狀態。
+
例子
`node stop --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. 使用 VMware 提供的步驟將執行ONTAP Select 的虛擬機器管理程式主機升級到 ESXi 7.0 或更高版本。
. 將節點移至線上狀態。
+
例子
`node start --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. 節點啟動後，驗證叢集是否健康。
+
例子

+
....
ESX-1N::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
....


.完成後
您應該使用 Deploy 管理公用程式執行叢集刷新操作。



== 使用 Deploy 升級多節點集群

您可以使用 Deploy 管理公用程式作為升級託管ONTAP Select多節點叢集的 VMware ESXi 虛擬機器管理程式的一部分。

.關於此任務
您必須對叢集中的每個節點執行此升級過程，一次一個節點。如果叢集包含四個或更多節點，則應依序升級每個 HA 對中的節點，然後再繼續升級下一個 HA 對。

.步驟
. 使用管理員帳戶透過 SSHSign inDeploy 實用程式 CLI。
. 將節點移至離線狀態。
+
例子
`node stop --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. 使用 VMware 提供的步驟將執行ONTAP Select 的虛擬機器管理程式主機升級到 ESXi 7.0 或更高版本。
+
有關詳細信息，請參閱準備升級 VMware ESXi。

. 將節點移至線上狀態。
+
例子
`node start --cluster-name <CLUSTERNAME> --node-name <NODENAME>`

. 節點啟動後，驗證儲存故障轉移是否已啟用以及叢集是否健康。
+
例子

+
....
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
....


.完成後
您必須對ONTAP Select叢集中使用的每個主機執行升級程序。所有 ESXi 主機升級完成後，您應該使用 Deploy 管理公用程式執行叢集刷新操作。



== 無需 Deploy 即可升級單節點集群

您可以升級託管ONTAP Select單節點叢集的 VMware ESXi 虛擬機器管理程序，而無需使用 Deploy 管理實用程式。

.步驟
. Sign inONTAP命令列介面並停止節點。
. 使用 VMware vSphere 確認ONTAP Select虛擬機器已關閉。
. 使用 VMware 提供的步驟將執行ONTAP Select 的虛擬機器管理程式主機升級到 ESXi 7.0 或更高版本。
+
有關詳細信息，請參閱準備升級 VMware ESXi。

. 使用 VMware vSphere 存取 vCenter 並執行下列操作：
+
.. 為ONTAP Select虛擬機器新增軟碟機。
.. 啟動ONTAP Select虛擬機。
.. 使用管理員帳戶透過 SSHSign inONTAP CLI。


. 節點啟動後，驗證叢集是否健康。
+
例子



....
ESX-1N::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
....
.完成後
您應該使用 Deploy 管理公用程式執行叢集刷新操作。



== 無需 Deploy 即可升級多節點集群

您可以升級託管ONTAP Select多節點叢集的 VMware ESXi 虛擬機器管理程序，而無需使用 Deploy 管理實用程式。

.關於此任務
您必須對叢集中的每個節點執行此升級過程，一次一個節點。如果叢集包含四個或更多節點，則應依序升級每個 HA 對中的節點，然後再繼續升級下一個 HA 對。

.步驟
. Sign inONTAP命令列介面並停止節點。
. 使用 VMware vSphere 確認ONTAP Select虛擬機器已關閉。
. 使用 VMware 提供的步驟將執行ONTAP Select 的虛擬機器管理程式主機升級到 ESXi 7.0 或更高版本。
. 使用 VMware vSphere 存取 vCenter 並執行下列操作：
+
.. 為ONTAP Select虛擬機器新增軟碟機。
.. 啟動ONTAP Select虛擬機。
.. 使用管理員帳戶透過 SSHSign inONTAP CLI。


. 節點啟動後，驗證儲存故障轉移是否已啟用以及叢集是否健康。
+
例子

+
....
ESX-2N_I2_N11N12::> storage failover show
Takeover
Node Partner Possible State Description
-------------- -------------- -------- ---------------------------
sdot-d200-011d sdot-d200-012d true Connected to sdot-d200-012d
sdot-d200-012d sdot-d200-011d true Connected to sdot-d200-011d
2 entries were displayed.
ESX-2N_I2_N11N12::> cluster show
Node Health Eligibility
--------------------- ------- ------------
sdot-d200-011d true true
sdot-d200-012d true true
2 entries were displayed.
....


.完成後
您必須對ONTAP Select叢集中使用的每個主機執行升級程序。
