---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: 您可以使用命令列介面就地升級現有的 Deploy 實用程式虛擬機器。 
---
= 升級ONTAP Select Deploy 實例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用命令列介面就地升級現有的 Deploy 實用程式虛擬機器。



== 開始之前

請確保在升級過程中不要使用 Deploy 執行任何其他任務。有關升級 Deploy 實用程式的資訊和限制，請參閱目前的發行說明。


NOTE: 如果您安裝了ONTAP Select Deploy 管理公用程式的舊實例，則應升級至目前版本。 ONTAPONTAP Select節點和ONTAP Select Deploy 元件將單獨升級。請參閱link:concept_adm_upgrading_nodes.html["升級ONTAP Select節點"^]了解更多詳情。



== 下載升級套件

要開始升級過程，您必須從 NetApp Support Site 下載適當的 Deploy 虛擬機器升級檔案。升級套件的格式為單一壓縮檔案。

.步驟
. 使用網頁瀏覽器存取 link:https://mysupport.netapp.com/site/["NetApp 支援網站"^]，然後從「下載」選單中選擇 *Downloads*。
. 向下捲動並選擇 *ONTAP Select Deploy Upgrade*。
. 選擇所需的升級套件版本。
. 查看最終用戶許可協議 (EULA) 並選擇*接受並繼續*。
. 選擇並下載適當的套件，並根據您的環境需求回應所有提示。




== 將軟體包上傳到 Deploy 虛擬機器

取得升級套件後，您必須將檔案上傳至 Deploy 虛擬機器。

.開始之前
您的本機工作站上必須備有升級檔案。您還必須擁有管理員使用者帳戶的密碼。

.關於此任務
此任務描述了將檔案上傳到 Deploy 虛擬機器的一種方法。可能還有其他更適合您環境的選項。

.步驟
. 在本機工作站的命令 shell 中，使用 scp 公用程式將映像檔上傳到 Deploy 虛擬機器。
+
例子

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.結果
升級檔案儲存在管理員使用者的主目錄中。



== 套用升級套件

將升級檔案上傳到 Deploy 虛擬機器後，即可套用升級。

.開始之前
您必須知道升級檔案在 Deploy 實用程式虛擬機器中的存放目錄。此外，請確保在執行升級時，Deploy 不會用於執行任何其他工作。

.步驟
. 使用管理員帳戶透過 SSHSign inDeploy 實用程式 CLI。
. 使用適當的目錄路徑和檔案名稱執行升級：
+
`deploy upgrade -package-path FILEPATH`

+
例子

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.完成後
在升級程序完成之前，系統會要求您建立 Deploy 虛擬機器組態的備份。此外，您也應該清除瀏覽器快取，以便檢視新建立的 Deploy 頁面。
